[server]
headless = true
port = 8501

[theme]
primaryColor = "#4caf50"
backgroundColor = "#f0f2f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#344767"
font = "sans serif"

[browser]
gatherUsageStats = false
